### ISSUE TITLE
Open??????

### ISSUE THREAD

**Issue by stanlok237** [stuykc/join-stuykc#1]
Shouldn't this be private considering it has sensitive material

**Comment by dannyqiu** [comment]
It should be private, but there are no private repositories on the stuykc github. Also, I will be changing the way forms are submitted, which means that there will be no need for credentials

**Comment by dannyqiu** [comment]
Newest version uses backend form submission instead of updating a spreadsheet directly. So now we don't have to worry about anyone else being able to see the responses.
